### ISSUE TITLE
Add a signature to map command

### ISSUE THREAD

**Issue by alexherbo2** [mawww/kakoune#2669]
### Prototype

```
map {scope} {mode} [signature] {key} {keys}
```

With _signature_ being a regular expression.

### Signatures

``` yaml
object:
- name: select-whole
  key: '<a-a>'
- name: select-whole-start
  key: '['
- name: select-whole-end
  key: ']'
- name: extend-whole-start
  key: '{'
- name: extend-whole-end
  key: '}'
- name: select-inner
  key: '<a-i>'
- name: select-inner-start
  key: '<a-[>'
- name: select-inner-end
  key: '<a-]>'
- name: extend-inner-start
  key: '<a-{>'
- name: extend-inner-end
  key: '<a-}>'
prompt:
- name: command
  key: ':'
- name: insert-output
  key: '!'
- name: append-output
  key: '<a-!>'
- name: pipe
  key: '|'
- name: pipe-to
  key: '<a-|>'
- name: pipe-keep
  key: '$'
- name: select
  key: 's'
- name: split
  key: 'S'
- name: keep
  key: '<a-k>'
- name: clear
  key: '<a-K>'
- name: select-next-match
  key: '/'
- name: select-previous-match
  key: '<a-/>'
- name: extend-next-match
  key: '?'
- name: extend-previous-match
  key: '<a-?>'
go-to:
- name: select
  key: 'g'
- name: extend
  key: 'G'
view:
- name: default
  key: 'v'
- name: lock
  key: 'V'
```

#### Objects

Selecting nodes with [kak-tree]:

``` kak
map global object select-(whole|inner) n -docstring 'Node' '<esc>:tree-select-node<ret>'
map global object (select|extend)-(whole|inner)-start n -docstring 'Node' '<esc>:tree-select-prev-node<ret>'
map global object (select|extend)-(whole|inner)-end n -docstring 'Node' '<esc>:tree-select-next-node<ret>'
```

#### Search

Jump to the next occurence while searching:

``` kak
map global prompt (select|extend)-(next|previous)-match <tab> <ret>/<up>
```

Issue: #1663

#### User prompts

Add a mapping to a prompt defined by user:

``` kak
define-command prompt-echo %{
  prompt -signature echo '❯ ' 'echo %val(text)'
}

map global prompt echo <c-n> 'Tchou'
```

[kak-tree]: https://github.com/ul/kak-tree
