### ISSUE TITLE
A: to end of line in yaml file followed by <space> and <c-r> eats spaces.

### ISSUE THREAD

**Issue by vbauerster** [mawww/kakoune#3117]
In `yaml` file, appending to end of line <kbd>A</kbd>, followed by `<space>` and `<c-r>"` eats spaces.
Suppose register `"` contains `Bold` and given following yaml file:

```yaml
font:
  bold:
    family: Iosevka
    style: Iosevka
```
Go to last line press `A<space><c-r>"`

Expected:
```yaml
font:
  bold:
    family: Iosevka
    style: Iosevka Bold
```
Got:
```yaml
font:
  bold:
    family: Iosevka
    style: IosevkaBold
```
First I thought, it's some plugin in my kakrc. But then I removed my kakrc file and nothing changed.
