### ISSUE TITLE
Use Cirrus

### ISSUE THREAD

**Issue by lenormf** [mawww/kakoune#3255]
Hi,

@t6 has implemented a `.cirrus.yml` file in #3249, inlined below:

```yaml
freebsd_task:
    freebsd_instance:
        image_family: freebsd-12-1
    gmake_script: pkg install -y gmake
    matrix:
        - name: freebsd_clang
        - name: freebsd_gcc
          gcc_script: pkg install -y gcc
          env:
              CXX: g++
    test_script: gmake test
    env:
        LC_ALL: en_US.UTF-8

linux_task:
    container:
        image: gcc:7
    locales_script:
        - apt-get update && apt-get -y install locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8
    matrix:
        - name: linux_clang
          env:
              CXX: clang++
          clang_script:
              - apt-get -y install clang
        - name: linux_gcc
    test_script: make test
    env:
        LC_ALL: en_US.UTF-8

macos_task:
    osx_instance:
        image: mojave-base
    test_script: make test
```

Build artefacts resulting from such a file can be found [here](https://cirrus-ci.com/build/5357709834059776).

As you can see, the manifest is much shorter and clearer than `.travis.yml`, and test builds on Cirrus start much earlier. Travis is known for being slow, and lately has errored-out of test builds for often.

Could we give Cirrus a try, and ultimately switch-over if it really is as good as it seems?

A badge can be added to the `README` file with the following:

```diff
diff --git a/README.asciidoc b/README.asciidoc
index 820946a0..05a172da 100644
--- a/README.asciidoc
+++ b/README.asciidoc
@@ -1,9 +1,11 @@
-= image:{logo}[K,30,30,link="{website}",title="Kakoune logo by p0nce"] Kakoune image:{travis-img}[link="{travis-url}"] image:{irc-img}[link="{irc-url}"]
+= image:{logo}[K,30,30,link="{website}",title="Kakoune logo by p0nce"] Kakoune image:{travis-img}[link="{travis-url}"] image:{cirrus-img}[link="{cirrus-url}"] image:{irc-img}[link="{irc-url}"]
 ifdef::env-github,env-browser[:outfilesuffix: .asciidoc]
 :logo: https://rawgit.com/mawww/kakoune/master/doc/kakoune_logo.svg
 :website: http://kakoune.org
 :travis-img: https://travis-ci.org/mawww/kakoune.svg?branch=master
 :travis-url: https://travis-ci.org/mawww/kakoune
+:cirrus-img: https://cirrus-ci.com/github/mawww/kakoune.svg
+:cirrus-url: https://cirrus-ci.com/github/mawww/kakoune
 :irc-img: https://img.shields.io/badge/IRC-%23kakoune-blue.svg
 :irc-url: https://webchat.freenode.net/?channels=kakoune
 :icons: font
```

HTH.
